  services:

    db:
      image: postgres:17.0-alpine3.20
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
      ports:
        - "5432:5432"

