"""add column bonus_points in table game

Revision ID: 349bf86d59a2
Revises: 8d6f5b781b58
Create Date: 2025-04-22 15:34:30.925816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349bf86d59a2'
down_revision: Union[str, None] = '8d6f5b781b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('bonus_points', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'bonus_points')
    # ### end Alembic commands ###
