"""add current player

Revision ID: 36bdf02b9f27
Revises: d30f014e64d4
Create Date: 2025-04-17 14:33:16.493082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36bdf02b9f27'
down_revision: Union[str, None] = 'd30f014e64d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_participants', 'turn_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('games', sa.Column('revealed_letters', sa.String(), nullable=False))
    op.add_column('games', sa.Column('current_player_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'game_participants', ['current_player_id'], ['participant_id'], ondelete='SET NULL')
    op.drop_column('games', 'revealed_letter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('revealed_letter', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'current_player_id')
    op.drop_column('games', 'revealed_letters')
    op.alter_column('game_participants', 'turn_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
