"""update_unique_index

Revision ID: d30f014e64d4
Revises: b1e31bad5898
Create Date: 2025-04-15 22:36:27.021346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd30f014e64d4'
down_revision: Union[str, None] = 'b1e31bad5898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_game', 'game_participants', ['user_id', 'game_id'])
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_constraint('uq_user_game', 'game_participants', type_='unique')
    # ### end Alembic commands ###
