name: Check homework
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Install Python 3.12
        run: uv python install 3.12
      - name: Install dependencies
        run: uv sync --group lint --frozen --no-cache
      - name: Run ruff
        run: |
          uv run ruff format --check
          uv run ruff check --no-fix
